import { ItemInfo } from "./ItemInterface";

export const animalsData: ItemInfo[] = [
  {
    nameRO: "Pisica",
    emoji: "🐱",
    singular: "Il gatto",
    plural: "I gatti",
  },
  {
    nameRO: "Caine",
    emoji: "🐶",
    singular: "Il cane",
    plural: "I cani",
  },
  {
    nameRO: "Pasare",
    emoji: "🐦",
    singular: "L'uccello",
    plural: "Gli uccelli",
  },
  {
    nameRO: "Elefant",
    emoji: "🐘",
    singular: "L'elefante",
    plural: "Gli elefanti",
  },
  {
    nameRO: "Leu",
    emoji: "🦁",
    singular: "Il leone",
    plural: "	I leoni",
  },
  {
    nameRO: "Urs",
    emoji: "🐻",
    singular: "L'orso",
    plural: "	Gli orsi",
  },
  {
    nameRO: "Cal",
    emoji: "🐴",
    singular: "Il cavallo",
    plural: "	I cavalli",
  },
  {
    nameRO: "Tigru",
    emoji: "🐯",
    singular: "La tigre",
    plural: "	Le tigri",
  },
  {
    nameRO: "Taur",
    emoji: "🐂",
    singular: "Il toro",
    plural: "	I tori",
  },
  {
    nameRO: "Broasca testoasa",
    emoji: "🐢",
    singular: "La tartaruga",
    plural: "Le tartarughe",
  },
  {
    nameRO: "Porc",
    emoji: "🐷",
    singular: "Il maiale",
    plural: "I maiali",
  },
  {
    nameRO: "Vaca",
    emoji: "🐮",
    singular: "La mucca",
    plural: "Le mucche",
  },
  {
    nameRO: "Oaie",
    emoji: "🐑",
    singular: "La pecora",
    plural: "Le pecore",
  },
  {
    nameRO: "Rata",
    emoji: "🦆",
    singular: "La papera",
    plural: "Le papere",
  },
  {
    nameRO: "Sarpe",
    emoji: "🐍",
    singular: "Il serpente",
    plural: "	I serpenti",
  },
  {
    nameRO: "Maimuta",
    emoji: "🐵",
    singular: "La scimmia",
    plural: "Le scimmie",
  },
  {
    nameRO: "Pinguin",
    emoji: "🐧",
    singular: "Il pinguino",
    plural: "I pinguini",
  },
  {
    nameRO: "Bufnita",
    emoji: "🦉",
    singular: "Il gufo",
    plural: "Gli gufi",
  },
  {
    nameRO: "Girafa",
    emoji: "🦒",
    singular: "La giraffa",
    plural: "Le giraffe",
  },
  {
    nameRO: "Camila",
    emoji: "🐪",
    singular: "Il cammello",
    plural: "I cammelli",
  },
  {
    nameRO: "Delfin",
    emoji: "🐬",
    singular: "Il delfino",
    plural: "I delfini",
  },
  {
    nameRO: "Crocodil",
    emoji: "🐊",
    singular: "Il coccodrillo",
    plural: "	I coccodrilli",
  },
  {
    nameRO: "Iepure",
    emoji: "🐰",
    singular: "Il coniglio",
    plural: "I conigli",
  },
  {
    nameRO: "Vulpe",
    emoji: "🦊",
    singular: "La volpe",
    plural: "Le volpi",
  },
  {
    nameRO: "Rechin",
    emoji: "🦈",
    singular: "Lo squalo",
    plural: "	Gli squali",
  },
  {
    nameRO: "Lup",
    emoji: "🐺",
    singular: "Il lupo",
    plural: "I lupi",
  },
];
