import { ItemInfo } from "./ItemInterface";

export const foodsData: ItemInfo[] = [
  {
    nameRO: "Mar",
    emoji: "🍎",
    singular: "La mela",
    plural: "Le mele",
  },
  {
    nameRO: "Para",
    emoji: "🍐",
    singular: "La pera",
    plural: "Le pere",
  },
  {
    nameRO: "Portocale",
    emoji: "🍊",
    singular: "L'arancia",
    plural: "Le arance",
  },
  {
    nameRO: "Lamaie",
    emoji: "🍋",
    singular: "Il limone",
    plural: "I limoni",
  },
  {
    nameRO: "Capsuni",
    emoji: "🍓",
    singular: "La fragola",
    plural: "Le fragole",
  },
  {
    nameRO: "Banana",
    emoji: "🍌",
    singular: "La banana",
    plural: "	Le banane",
  },
  {
    nameRO: "Struguri",
    emoji: "🍇",
    singular: "L'uva",
    plural: "L'uva",
  },
  {
    nameRO: "Rodie",
    img: "https://static-00.iconduck.com/assets.00/pomegranate-emoji-1893x2048-fkc5eejy.png",
    singular: "Il melograno",
    plural: "	I melograni",
  },
  {
    nameRO: "Kiwi",
    emoji: "🥝",
    singular: "Il kiwi",
    plural: "Gli kiwi",
  },
  {
    nameRO: "Piersica",
    emoji: "🍑",
    singular: "La pesca",
    plural: "Le pesche",
  },
  {
    nameRO: "Caisa",
    emoji: "🟠",
    singular: "L'albicocca",
    plural: "Le albicocche",
  },
  {
    nameRO: "Pepene galben",
    emoji: "🍈",
    singular: "Il melone",
    plural: "I meloni",
  },
  {
    nameRO: "Ananas",
    emoji: "🍍",
    singular: "L'ananas",
    plural: "Gli ananas",
  },
  {
    nameRO: "Cireasa",
    emoji: "🍒",
    singular: "La ciliegia",
    plural: "Le ciliegie",
  },
  {
    nameRO: "Mango",
    emoji: "🥭",
    singular: "Il mango",
    plural: "I manghi",
  },
  {
    nameRO: "Pruna",
    emoji: "🫐",
    singular: "La prugna",
    plural: "Le prugne",
  },
  {
    nameRO: "Morcov",
    emoji: "🥕",
    singular: "La carota",
    plural: "Le carote",
  },
  {
    nameRO: "Rosie",
    emoji: "🍅",
    singular: "Il pomodoro",
    plural: "	I pomodori",
  },
  {
    nameRO: "Castravete",
    emoji: "🥒",
    singular: "Il cetriolo",
    plural: "I cetrioli",
  },
  {
    nameRO: "Ardei",
    emoji: "🌶️",
    singular: "Il peperone",
    plural: "I peperoni",
  },
  {
    nameRO: "Usturoi",
    emoji: "🧄",
    singular: "L'aglio",
    plural: "Gli aglio",
  },
  {
    nameRO: "Ceapa",
    emoji: "🧅",
    singular: "La cipolla",
    plural: "Le cipolle",
  },
  {
    nameRO: "Salata",
    emoji: "🥗",
    singular: "L'insalata",
    plural: "Le insalate",
  },
  {
    nameRO: "Varza",
    emoji: "🥬",
    singular: "Il cavolo",
    plural: "I cavoli",
  },
  {
    nameRO: "Dovlecel",
    img: "https://cdn-icons-png.flaticon.com/512/3944/3944047.png",
    singular: "La zucchina",
    plural: "	Le zucchine",
  },
  {
    nameRO: "Vinete",
    emoji: "🍆",
    singular: "La melanzana",
    plural: "Le melanzane",
  },
  {
    nameRO: "Cartofi",
    emoji: "🥔",
    singular: "La patata",
    plural: "Le patate",
  },
  {
    nameRO: "Ciuperci",
    emoji: "🍄",
    singular: "Il fungo",
    plural: "I funghi",
  },
  {
    nameRO: "Fasole",
    emoji: "🫘",
    singular: "Il fagiolo",
    plural: "I fagioli",
  },
  {
    nameRO: "Salata Verde",
    emoji: "🥗",
    singular: "La lattuga",
    plural: "Le lattughe",
  },
  {
    nameRO: "Dovleac",
    emoji: "🎃",
    singular: "La zucca",
    plural: "Le zucche",
  },
  {
    nameRO: "Telina",
    img: "https://cdn-icons-png.flaticon.com/512/7230/7230856.png",
    singular: "Il sedano",
    plural: "I sedani",
  },
  {
    nameRO: "Piper",
    img: "https://cdn.emojidex.com/emoji/seal/pepper.png?1453371367",
    singular: "Il pepe",
    plural: "	I pepe",
  },
  {
    nameRO: "Zahar",
    img: "https://pngimg.com/d/sugar_PNG98791.png",
    singular: "Lo zucchero",
    plural: "Gli zuccheri",
  },
  {
    nameRO: "Sare",
    emoji: "🧂",
    singular: "Il sale",
    plural: "I sali",
  },
  {
    nameRO: "Miere",
    emoji: "🍯",
    singular: "Il miele",
    plural: "I mieli",
  },
  {
    nameRO: "Cafea",
    emoji: "☕",
    singular: "Il caffè",
    plural: "	I caffè",
  },
  {
    nameRO: "Bere",
    emoji: "🍺",
    singular: "La birra",
    plural: "	Le birre",
  },
  {
    nameRO: "Ceai",
    emoji: "🍵",
    singular: "Il tè",
    plural: "I tè",
  },
  {
    nameRO: "Vin",
    emoji: "🍷",
    singular: "Il vino",
    plural: "I vini",
  },
  {
    nameRO: "Paine",
    emoji: "🍞",
    singular: "Il pane",
    plural: "I pani",
  },
  {
    nameRO: "Orez",
    emoji: "🍚",
    singular: "Il riso",
    plural: "	I risi",
  },
  {
    nameRO: "Clatita",
    emoji: "🥞",
    singular: "La frittella",
    plural: "Le frittelle",
  },
  {
    nameRO: "Pizza",
    emoji: "🍕",
    singular: "La pizza",
    plural: "Le pizze",
  },
  {
    nameRO: "Covrig",
    emoji: "🥨",
    singular: "Il pretzel",
    plural: "I pretzel",
  },
  {
    nameRO: "Cornet",
    emoji: "🥐",
    singular: "La brioche",
    plural: "Le brioche",
  },
  {
    nameRO: "Hot Dog",
    emoji: "🌭",
    singular: "L'hot dog",
    plural: "Gli hot dog",
  },
  {
    nameRO: "Hamburger",
    emoji: "🍔",
    singular: "L'hamburger",
    plural: "Gli hamburger",
  },
  {
    nameRO: "Carne de vita",
    emoji: "🥩",
    singular: "La carne di manzo",
    plural: "La carne di manzo",
  },
  {
    nameRO: "Carne de porc",
    emoji: "🍖",
    singular: "La carne di maiale",
    plural: "La carne di maiale",
  },
  {
    nameRO: "Carne de pui",
    emoji: "🍗",
    singular: "La carne di pollo",
    plural: "La carne di pollo",
  },
  {
    nameRO: "Cartofi Prajiti",
    emoji: "🍟",
    singular: "Le patatine fritte",
    plural: "Le patatine fritte",
  },
  {
    nameRO: "Popcorn",
    emoji: "🍿",
    singular: "Il popcorn",
    plural: "Il popcorn",
  },
  {
    nameRO: "Taco",
    emoji: "🌮",
    singular: "Il taco",
    plural: "I taco",
  },
  {
    nameRO: "Sandwich",
    emoji: "🥪",
    singular: "Il panino",
    plural: "	I panini",
  },
  {
    nameRO: "Peste",
    emoji: "🐟",
    singular: "Il pesce",
    plural: "I pesci",
  },
  {
    nameRO: "Oua",
    emoji: "🥚",
    singular: "L'uovo",
    plural: "Le uova",
  },
];
