import { ItemInfo } from "./ItemInterface";

export const objectsData: ItemInfo[] = [
  {
    nameRO: "Masa",
    img: "https://cdn-icons-png.flaticon.com/512/638/638247.png",
    singular: "Il tavolo",
    plural: "I tavoli",
  },
  {
    nameRO: "Ghiozdan",
    emoji: "🎒",
    singular: "Lo zaino",
    plural: "Gli zaini",
  },
  {
    nameRO: "Scaun",
    emoji: "🪑",
    singular: "La sedia",
    plural: "Le sedie",
  },
  {
    nameRO: "Pat",
    emoji: "🛏️",
    singular: "Il letto",
    plural: "I letti",
  },
  {
    nameRO: "Geanta",
    emoji: "👜",
    singular: "La borsa",
    plural: "Le borse",
  },
  {
    nameRO: "Hartie",
    emoji: "📜",
    singular: "La carta",
    plural: "Le carte",
  },
  {
    nameRO: "Carte",
    emoji: "📖",
    singular: "Il libro",
    plural: "I libri",
  },
  {
    nameRO: "Oglinda",
    emoji: "🪞",
    singular: "Lo specchio",
    plural: "Gli specchi",
  },
  {
    nameRO: "Canapea",
    emoji: "🛋️",
    singular: "Il divano",
    plural: "I divani",
  },
  {
    nameRO: "Usa",
    emoji: "🚪",
    singular: "La porta",
    plural: "Le porte",
  },
  {
    nameRO: "Stilou",
    emoji: "🖊️",
    singular: "La penna",
    plural: "Le penne",
  },
  {
    nameRO: "Telefon",
    emoji: "📱",
    singular: "Il telefono",
    plural: "I telefoni",
  },
  {
    nameRO: "Calculator",
    emoji: "🖥️",
    singular: "Il computer",
    plural: "I computer",
  },
  {
    nameRO: "Cheie",
    emoji: "🔑",
    singular: "La chiave",
    plural: "Le chiavi",
  },
  {
    nameRO: "Portofel",
    emoji: "👛",
    singular: "Il portafoglio",
    plural: "I portafogli",
  },
  {
    nameRO: "Ochelari",
    emoji: "🕶️",
    singular: "Gli occhiali",
    plural: "Le macchine",
  },
  {
    nameRO: "Masina",
    emoji: "🚗",
    singular: "La macchina",
    plural: "La macchina",
  },
  {
    nameRO: "Aparat foto",
    emoji: "📷",
    singular: "La fotocamera",
    plural: "Le fotocamere",
  },
  {
    nameRO: "Birou",
    img: "https://cdn-icons-png.flaticon.com/512/638/638247.png",
    singular: "La scrivania",
    plural: "Le scrivanie",
  },
  {
    nameRO: "Caiet",
    emoji: "📝",
    singular: "Il quaderno",
    plural: "I quaderni",
  },
  {
    nameRO: "Ceas",
    emoji: "⏰",
    singular: "Il orologio",
    plural: "L'orologio",
  },
  {
    nameRO: "Lampa",
    emoji: "💡",
    singular: "La lampada",
    plural: "Le lampade",
  },
  {
    nameRO: "Fereastra",
    emoji: "🪟",
    singular: "La finestra",
    plural: "Le finestre",
  },
  {
    nameRO: "Televizor",
    emoji: "📺",
    singular: "La TV",
    plural: "Le TV",
  },
  {
    nameRO: "Ziar",
    emoji: "📰",
    singular: "Il giornale",
    plural: "I giornali",
  },
];
